### ISSUE TITLE
mesh

### ISSUE THREAD

**Issue by fab1an2** [br101/libuwifi#10]
Is possible create a mesh network using sending and receiving data trought small computers? (for example esp8266)

I need similar https://reticulum.network/ but without using tcp ip.
Only direct connections. e.g. sending data while the two devices pass each other for several seconds.

Dynamicaly sending and change topology of network. Forwarding data taken from other nodes.

**Comment by br101** [comment]
Not really a suitable issue for libuwifi because its out of scope for this small little library ;-)

Generally speaking i think it should be possible, but you have to check the possibilities of your device (esp8266 or maybe esp32) to send and receive arbitrary packets thru wifi.
