### ISSUE TITLE
where is idf_component_register ?

### ISSUE THREAD

**Issue by fab1an2** [br101/libuwifi#11]
I download repo and create:
$mkdir build; cd build
$cmake ..
and get error

```
CMake Error at CMakeLists.txt:3 (idf_component_register):
  Unknown CMake command "idf_component_register".


CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.28)

```

**Comment by br101** [comment]
The CMakeLists.txt file is for including libuwifi into an ESP-IDF based project, not for compiling libuwifi in other situations, as mentioned in that file. For building libuwifi you use a simple "make" command.
