### ISSUE TITLE
OpenWrt: libubox has some struct definition of list_head

### ISSUE THREAD

**Issue by PolynomialDivision** [br101/libuwifi#7]
`libubox` defines `list_head` and `list.h` that is included in `ccan` which is included in `libuwifi`.
Currently I'm doing something like this:

     // redefine list_head because in libubox
     #define list_head horst_list_head
     #include <uwifi/node.h>
     #undef list_head

`libubox` is some very famous library for standard functions and list stuff in OpenWrt.

**Comment by br101** [comment]
Yes, I've had that problem before... looks like a smart solution... i will review it more in a couple of days...

**Comment by br101** [comment]
hey, i solved it differently now, by integrating ccan list more and adding a cc_ prefix to avoid name clashes. please check it out... thanks
